import type { Product3DConfig } from './types';

export const PRODUCT_3D_CONFIG: readonly Product3DConfig[] = [
  {
    id: 'original',
    name: 'STILL WATER',
    index: '01',
    headline: 'THE\nESSENTIAL.',
    description: 'Still water in infinitely recyclable aluminium.',
    accent: '#C8C8C8',
    background: '#F4F1EB',
    theme: 'light',
    capacity: '500ML',
    modelUrl: '/models/drop-original.glb',
    modelReady: false,
    fallbackImage: '/assets/turntable/original-front.png',
    modelScale: 1,
    modelPositionY: 0,
  },
  {
    id: 'mint',
    name: 'MINT WATER',
    index: '02',
    headline: 'WATER.\nAS IT SHOULD BE.',
    description: 'Crisp still water with a clean mint infusion.',
    accent: '#A987E9',
    background: '#08090B',
    theme: 'dark',
    capacity: '330ML',
    modelUrl: '/models/drop-mint.glb',
    modelReady: false,
    fallbackImage: '/assets/turntable/mint-front.png',
    modelScale: 1,
    modelPositionY: 0,
  },
  {
    id: 'athlete',
    name: 'ATHLETE EDITION',
    index: '03',
    headline: 'BUILT TO\nPERFORM.',
    description: 'Purpose-built hydration for high-intensity movement.',
    accent: '#EFEFEF',
    background: '#0A0A0B',
    theme: 'dark',
    capacity: '330ML',
    modelUrl: '/models/drop-athlete.glb',
    modelReady: false,
    fallbackImage: '/assets/turntable/athlete-front.png',
    modelScale: 1,
    modelPositionY: 0,
  },
  {
    id: 'clove',
    name: 'CLOVE WATER',
    index: '04',
    headline: 'FORM,\nREFINED.',
    description: 'Aromatic clove infusion in recyclable aluminium.',
    accent: '#9B5B4F',
    background: '#F4F1EB',
    theme: 'light',
    capacity: '500ML',
    modelUrl: '/models/drop-clove.glb',
    modelReady: false,
    fallbackImage: '/assets/clove_can_transparent_fixed.png',
    modelScale: 1,
    modelPositionY: 0,
  },
] as const;
